packages:
 - nodejs 
 - npm
 - git 

runcmd:
 - git clone https://github.com/Kartik1397/websocket-load-tester
 - cd websocket-load-tester && npm i
 - echo "* soft nofile 999999 \n* hard nofile 999999" >> /etc/security/limits.conf
 - sysctl -w net.ipv4.ip_local_port_range="20000 65535"
